/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Buttons: typeof import('./src/components/buttons.vue')['default']
    copy: typeof import('./src/components/lift-one copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Floorbutton: typeof import('./src/components/floorbutton.vue')['default']
    LiftOne: typeof import('./src/components/lift-one.vue')['default']
    OtherButtons: typeof import('./src/components/otherButtons.vue')['default']
    OutButtons: typeof import('./src/components/outButtons.vue')['default']
    Pannel: typeof import('./src/components/pannel.vue')['default']
    Pannels: typeof import('./src/components/pannels.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
